[tool.poetry]
name = "secure-ai-toolset"
version = "0.0.7"
description = "python toolset to secure AI agents with secret provisioning, authentication, call monitoring and authorization"
readme = "README.md"
license = "Apache Software License (Apache-2.0)"
authors = ["CyberArk <acyberark@cyberark.com>"]
 
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
 
[tool.poetry.dependencies]
python = ">=3.11.0, <4.0"
boto3 = "*"
 
[tool.poetry.dev-dependencies]
pytest = "*"
yapf = "^0.43.0"
isort = "^6.0.1"
autoflake = "^2.3.1"
toml = "^0.10.2"