[project]
name = "secure-ai-toolset"
version = "0.1.0"
description = ""
authors = [
    {name = "GilAddaCyberArk",email = "gil.adda@cyberark.com"}
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pydantic (>=2.10.6,<3.0.0)",
    "pylint (>=3.3.5,<4.0.0)"
]

[tool.poetry]
packages = [
    { include = "secure_ai_toolset", from = "secure-ai-toolset" }
]

[tool.poetry.group.aws.dependencies]
boto3 = "*"

[tool.poetry.group.dev.dependencies]
pytest = "*"
yapf = "^0.43.0"
isort = "^6.0.1"
autoflake = "^2.3.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
