[project]
name = "secure-ai-toolset"
version = "0.1.0"
description = ""
authors = [
    {name = "GilAddaCyberArk",email = "gil.adda@cyberark.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
]

[tool.poetry]
packages = [{include = "secure_ai_toolset", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
