name: Release

on:
  push:
    branches:
      - main
  pull_request: # Trigger on pull requests
    branches:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure label exists
        if: github.event_name == 'pull_request'
        run: |
          gh label list | grep -q "${{ github.head_ref }}" || gh label create "${{ github.head_ref }}" --color "#0366d6"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add branch name label
        if: github.event_name == 'pull_request'
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-label "${{ github.head_ref }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release without label
        if: github.ref == 'refs/heads/main'
        run: |
          gh release create "$(date +'%Y%m%d%H%M%S')" --title "Release $(date +'%Y-%m-%d %H:%M:%S')" --notes "Automated release from main branch"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install poetry
          npm install -g semantic-release

      - name: Run semantic release
        run: semantic-release publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
